### ISSUE TITLE
Demo page not long enough on larger screens

### ISSUE THREAD

**Issue by alexcroox** [theonion/fartscroll.js#3]
Need to add some more filler content for larger screens (tested with 27" iMac) to initiate demo scrolling :D

http://al3x.me/Orxs

Looking forward to using this plugin in client projects, thank you!

**Comment by lloydwatkin** [comment]
Have put in pull request #7 for this :)

**Comment by makc** [comment]
nothing happens in tthe demo page on my 15" laptop

**Comment by alexcroox** [comment]
Browser? OS? Sound volume level? :P

**Comment by makc** [comment]
ie9/win7/100%

but it's noisy here. will check again later.

**Comment by csinchok** [comment]
This is fixed now, thanks to #7.
